# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        if: ${{ github.event.created && startsWith(github.ref, 'refs/tags/') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}